[package]
name = "corporateStandards"
version = "0.1.0"
edition = "2021"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.'cfg(windows)'.dependencies]
native-dialog = "0.7.0"
reqwest = "0.12.9"
tokio = { version = "1", features = ["full"] }
winreg = "0.52.0"
dirs = "5.0.1"